cache: bundler
sudo: false
rvm:
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - ruby-head
gemfile:
  - gemfiles/rails4.2.gemfile
  - gemfiles/rails5.0.gemfile
  - gemfiles/rails5.1.gemfile
  - gemfiles/rails5.2.gemfile
  - gemfiles/rails6.0.gemfile
script: "bundle exec rake test"
matrix:
  exclude:
    - rvm: 2.4
      gemfile: gemfiles/rails6.0.gemfile
    - rvm: 2.7
      gemfile: gemfiles/rails4.2.gemfile
  allow_failures:
    - rvm: ruby-head
