cache: bundler
sudo: false
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.6
  - 2.3.3
  - 2.4.1
gemfile:
  - gemfiles/rails3.2.gemfile
  - gemfiles/rails4.2.gemfile
  - gemfiles/rails5.0.gemfile
  - gemfiles/rails5.1.gemfile
  - gemfiles/rails5.2.gemfile
script: "bundle exec rake test"
matrix:
  exclude:
    - rvm: 2.0.0
      gemfile: gemfiles/rails5.0.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rails5.1.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rails5.2.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails5.0.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails5.1.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails5.2.gemfile
    - rvm: 2.4.1
      gemfile: gemfiles/rails3.2.gemfile
