cache: bundler
sudo: false
rvm:
  - 2.2
  - 2.3
  - 2.4
gemfile:
  - gemfiles/rails3.2.gemfile
  - gemfiles/rails4.2.gemfile
  - gemfiles/rails5.0.gemfile
  - gemfiles/rails5.1.gemfile
  - gemfiles/rails5.2.gemfile
script: "bundle exec rake test"
matrix:
  exclude:
    - rvm: 2.4
      gemfile: gemfiles/rails3.2.gemfile
